//OBJETOS LITARERALES != OBJETOS DE LA PROGRAMACION ORIENTADA A OBJETOS

//TAMBIEN SE LES CONOCE EN OTROS LENGUAJES DE PROGRAMACION COMO MAPA/MAPS, O ARREGLOS ASOCIATIVOS/ ASOCIATIVE ARRAYS

const jaguar ={
    nombre:"Jaguar",
    color: "Amarillo",
};

//PARA ACCEDER A LAS PROPIEDADES DE UN OBJETO
//Puedo usar la notacon de punto/ dot notation 
console.log("NOTACION DE PUNTO", jaguar.nombre);
console.log("NOTACION DE PUNTO",jaguar.color);

//TAMBIEN PUEDES ACCEDER A SUS VALORES , MEDIANTE LA NOTACION DE CORCHETES CUADRADO/SQUARE BRAKECTS NOTATION 

console.log("NOTACION DE CORCHETES CUADRADOS", jaguar["nombre"]);
console.log("NOTACION DE CORCHETES CUADRADOS", jaguar["color"]);

